src/io/decoder.ts
Fix for https://github.com/stoqey/ib/issues/23
=> Issue-23: fix decodeMsg_POSITION_MULTI

src/api/order/trailingStop.ts, src/index.ts
Add trailingPercent and documentation to TrailingStopOrder
(+ add IBApiCreationOptions to index.ts, was missing on docu)
=> Add trailingPercent and documentation to TrailingStopOrder

src/dev/app.ts, src/io/decoder.ts
PR for https://github.com/stoqey/ib/issues/55
- Add decoder function for REROUTE_MKT_DATA, REROUTE_MKT_DEPTH and MARKET_RULE
- Make sure message buffer is drained if decoding fails
=> Add missing decoder functions

src/api-next/api-next.ts, src/tests/unit/api-next/get-managed-accounts.test.ts, src/tools/managed-accts.ts
Add` getManagedAccounts(): Promise<string[]>` function to IBApiNext for getting list of all managed accounts..
=> Add IBApiNext.getManagedAccounts

src/core/io/encoder.ts
Fix for https://github.com/stoqey/ib/issues/66
Add missing condition type token.
=> Fix order conditions (add order type token)

package.json, yarn.lock
=> fix audit remove ts-lint

package.json, yarn.lock
- This small PR moves some of the dependencies to dev dependencies
=> move deps to dev

src/api/api.ts, src/tests/unit/api/order/reqAllOpenOrders.test.ts
- Fix order status event parameters
=> - fix order status

.github/workflows/publish.yml
=> Upgrade publish node from 12 to 14

src/tests/unit/api/order/placeOrder.test.ts, src/tools/account-summary.ts, src/tools/common/ib-api-next-app.ts, src/tools/contract-details.ts, src/tools/historical-data-updates.ts, src/tools/historical-data.ts, src/tools/historical-ticks-bid-ask.ts, src/tools/historical-ticks-last.ts, src/tools/historical-ticks-mid.ts, src/tools/market-data.ts, src/tools/pnl-single.ts, src/tools/pnl.ts
=> Review all tools and improve tools host/port logic

README.md
Adds a version and code quality badge to README.md
=> Add version and code quality badge

src/index.ts
This will allow to import the bar size settings from top-level:
```ts
import { BarSizeSetting } from "@stoqey/ib";
```
=> Top-level export for bar size settings

src/api/contract/forex.ts, src/common/configuration.ts, src/core/io/socket.ts, src/tools/account-summary.ts, src/tools/historical-data.ts, src/tools/pnl-single.ts, src/tools/pnl.ts, src/tools/positions.ts
Let's get A+ code quality - fixes issues as listed here: 
https://lgtm.com/projects/g/stoqey/ib
=> Fix lgtm issues

.vscode/launch.json, src/api-next/api-next.ts, src/api-next/index.ts, src/api-next/order/open-order-update.ts, src/api-next/order/open-order.ts, src/tests/unit/api-next/get-all-open-orders.test.ts, src/tools/open-orders.ts
**OpenOrders**
- GetAllOpenOrders
Added getAllOpenOrders functionality in ibnext service.
=> Apinext open orders

.vscode/launch.json, sample.env, src/api-next/api-next.ts, src/common/configuration.ts, src/tests/unit/api-next/next-valid-order-id.test.ts, src/tests/unit/api-next/place-order.test.ts, src/tools/common/ib-api-next-app.ts, src/tools/modify-order.ts, src/tools/next-valid-order-id.ts, src/tools/place-new-order.ts, src/tools/place-order.ts, yarn.lock
Adds IBApiNext
- placeOrder
- placeNewOrder
- modifyOrder
- cancelOrder
- cancelAllOrders
=> added next valide order id functionality

README.md, src/api-next/api-next.ts, src/tests/unit/api-next/get-contract-details.test.ts, src/tools/contract-details.ts
See https://github.com/stoqey/ib/issues/131
=> Change getContractDetails to return a Promise

src/api/contract/future.ts
See https://github.com/stoqey/ib/issues/133
=> Update Future class constructor signature

src/api-next/api-next.ts, src/tools/market-data-single.ts, src/tools/market-data.ts
this method will return a Promise to make snapshots of market data.
=> getMarketDataSingle implementation

src/api-next/account/account-update.ts, src/api-next/api-next.ts, src/api-next/index.ts, src/api-next/order/open-order-update.ts, src/api-next/position/position.ts, src/tools/open-orders.ts
New API call implemented for ApiNext:
getAccountUpdates
=> getAccountUpdates implemented

src/core/api-next/auto-connection.ts, src/core/io/socket.ts, src/tools/common/ib-api-next-app.ts
Some minor corrections in log messages related to connection
=> typo fix in log messages

src/api-next/api-next.ts
onUpdateMktDepthL2 handle insert and update operations the same way, which is I think a mistake because I got the following output:
[1] {
[1]   bids: Map(3) {
[1]     0 => { price: 154.32, marketMaker: 'ARCA', size: 7, isSmartDepth: true },
[1]     1 => { price: 154.32, marketMaker: 'BATS', size: 1, isSmartDepth: true },
[1]     2 => {
[1]       price: 154.32,
[1]       marketMaker: 'DRCTEDGE',
[1]       size: 1,
[1]       isSmartDepth: true
[1]     }
[1]   },
[1]   asks: Map(3) {
[1]     0 => { price: 154.33, marketMaker: 'ARCA', size: 5, isSmartDepth: true },
[1]     1 => { price: 154.33, marketMaker: 'BATS', size: 6, isSmartDepth: true },
[1]     2 => { price: 154.33, marketMaker: 'BATS', size: 6, isSmartDepth: true }
[1]   }
[1] }
notice the last data line which repeats leading to …
=> getMarketDepth bug fix

package.json, src/core/io/socket.ts, yarn.lock
This may seem surprising, but it solves the connection issue [https://github.com/stoqey/ib/issues/162](https://github.com/stoqey/ib/issues/162)
=> Connect issue

src/api/contract/combo.ts
that is nesarry for place combo order
=> feat: add combo leg propery.

src/api-next/api-next.ts, src/common/errorCode.ts, src/tools/market-data-single.ts, src/tools/market-data.ts
Should improve the results from getMarketData
=> Bug fix for issue #160

README.md
Please don't hesitate to shoot us a message on discord https://discord.gg/T4VjBrqGtK
=> fix(ibkr): refer to simpler ibkr
