- src/incoming.ts
Option greeks what values greater than 1 do not work properly as they are limited to 1 and if greater, it will be set Number.MAX_VALUE.
This is not on sync with Java implementation and causes the issue that values greater 1 cannot be displayed, as they are Number.MAX_VALUE.
This PR is about to fix this issue and align the Typescript code to what Java code is doing.
> Fix option greeks greater 1

- .gitignore
- .vscode/settings.json
- package-lock.json
- package.json
- tsconfig.json
This PR does introduce support for TypeDoc (https://typedoc.org/).
I'm planning to document new / reworked code with JS/TSDoc and and want to be able generate documentation from that, so that I verify if links works correctly, or on general, if it looks / reads nicely.
You can use 'npm run doc' to generate code documentation on /typedoc folder (although you won't see much useful yet, there is not a of documentation yet on the code ;))
Do "npm install" first, there is a new typedoc dev dependency.
> Introduce Typedoc.

- .vscode/launch.json
- .vscode/tasks.json
- examples/index.ts
- package.json
This PR does not affect any functionality on the library, but it will make lazy-developer live easier.
The the changes:
- Adds a new dependency to ts-node-dev. This is tool that monitors all ts code files and if it something change, it does a re-transpile / restart the build process.  Also added a VSCode build task, so you can start it with Shift+Ctrl+B.
- Added a new 'dev' script. 
"npm run dev" will start the ts-node-dev. So you can start to write code and each time you save the changes, it will re-build.
- Added a new 'dev:debug' script. 
This will attach the debugger to the ts-node-dev. Also added a VSCode launch task, so you can run it with F5.
Background: the example folder will get *.ts files in parallel to the existing *.js files, which provide Typescript sample code, but more …
> Add support for ts-node-dev

- src/api/contract/contractDetails.ts
- src/io/decoder.ts
ContractDetails.underSecType is string type on current API, but actually we have a SecType enum for that - changed it.
> Change ContractDetails.underSecType from string type to SecType.

- src/io/controller.ts
- src/io/decoder.ts
- src/io/socket.ts
While issue https://github.com/stoqey/ib/issues/23 is fixed, it showed two additional issues that are addressed by this PR:
1) The V100 allows to check for message boundaries. It sends the length of the message, followed by the tokens.
So we can verify if a decoder function actually did read all token it actually needs to read. Also we can drain any remaining any remaining tokens up next message start, so that decoding of other messages continues to to work, also if one decoder function is buggy.
Also we can verify if a decoder function tries to read past the message boundary and stop it form doing so.
2) There no useful error output at all if a decoding error happens - did improve that.
For testing purpose I did modify decodeMsg_POSITION to read one token than is it should. Decoding of …
> Improve robustness against decoding errors when using V100 protocol.

- src/io/encoder.ts
- src/io/socket.ts
As found on https://github.com/stoqey/ib/issues/29 this PR fixes the placeOrder on server version >= 103 (change on encoder)
While testing it and trying if works on old server version, I noticed that pre-V100 mode is broken all together, fixed as well (change on socket)
> - Fix placeOrder on server version >= 103

- package.json
- src/api/api.ts
During working on IBApiNext I have noticed the following message on console:
(node:2620) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pnlSingle listeners added to [IBApi]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
Reason is that node EventEmitter assumes that there is a memory leak if there are more than 10 listeners on an EventEmitter.
However, for us however this is a normal quite usecase.  Example: I want PnL of every position, so I do reqPnLSingle for every position and might want to have a pnlSingle event handler for every position as well - which will lead to this warning if you have more than 11 positions.
The warning does not seem to have any real effect, still it anoying. …
> Switch from EventEmitter to EventEmitter3

- src/io/socket.ts
This is a draft pull request to handle partial data being received on the IB connection socket.
The data parsing method appears to previously have been biased to assume that each call of the event handler would have a full and complete response from the IB server. However, that does not correctly handle cases where the socket might have buffered data from multiple calls ( or any other number of scenarios where the data received is partial ) and require that prior data that was received may in fact be part of a valid-yet-not-complete send on the part of the gateway / TWS.
This PR:
* Buffers data from previous calls and attempts to dispatch messages as they become fully formed
* Only buffer the data that has not yet been fully read
* Handle cases where the data parsing exceeds what the max …
> Handle Partial Data

- README.md
- src/api/api.ts
- src/io/controller.ts
- src/io/socket.ts
I have some auto-reconnect code in my project which will re-connect if there is no more response for some time. Sometimes (when I force connection drop), TWS does not notice the lost connection immediately and so there still is an active session for my client id ad TWS reject the re-connect (ID already exists).
Therefor I would like to use new client id on ever re-connect, but right now this is not possible w/o re-creating the whole IBApi object. So solve that, IBApi.connect now has a an (optional) clientId argument and IBApiCreationOptions.clientId has been deprecated.
I have also added some information about the "Deprecation Process" on readme. 
Basically, if we want to get rid of something we add "@depricated" to give users some time to migrate and after some more time remove it.
All …
> Add clientId argument to IBApi.connect function

- src/io/socket.ts
This PR addresses something noticed while working on #42 
In the course of working on the decoder, it seemed as if method of creating a duplicate array and copying data from the buffer then using `TextDecoder` to decode it could be made more efficient by using `Buffer.slice` to create a windowed view into the bytestream, and `Buffer.toString` rather than `TextDecoder` to use a "built in" facility of Buffer to retrieve the results.
> Reduce Copies In Decoder

- src/api/api.ts
- src/io/decoder.ts
- src/io/encoder.ts
This PR addresses issues w/ the `reqHistoricalData` method
It:
* Fixes an issue where the client incorrectly sent a `version` with the initial request. This should only happen when the server version is `< 124`, as per the Java client
* Only check and for attempt to read the `hasGaps` token if the server is sending it ( as above, if the version is `< 124` ). Note that the Java client outright discards this value, but here it is maintained
* Add support to the decoder for actually processing real time updates as they are received rather than erroring / dropping them
* Fix the typings for the `reqHistoricalData` and historical data real time event listeners. Previously they stated that they would receive an `IB.Bar` object; this is incorrect. They will instead be called with arguments …
> Fix historical data

- src/api/api.ts
This PR ensures that the `execDetails` event passes types the listener object according to what the decoder sends
> Add Execution Typing to Listener

- src/api/api.ts
- src/io/decoder.ts
This PR fixes a few issues with `reqCompletedOrders`:
* The typing on the completed order listener is adjusted to reflect the fact that the decoder does in fact provide a `Contract`, `Order` and `OrderState` object
* The completed order decoder has been adjusted to accommodate the presence of a `dontUseAutoPriceForHedge` field present for specific client / server pairings
* A typo is fixed to allow for the `COMPLETED_ORDERS_END` event to be handled correctly
> Fix completed orders

- src/io/controller.ts
Up to now it was required to call api.connect(), wait for the EventName.connected and then it was possible to call API functions w/o getting an error.
This is because all commands, including connect, are posted into the command-queue, which is in running-mode right from the beginning. So you call reqSomething, command will dispatch into encoder and encoder will error because it doesn't know server yet (and even it would, there is no TCP connection on the socket yet).
We can solve that easily by starting up command queue in pause-mode and not posting connect/disconnect to queue but to socket directly. So you can call reqSomething, wich will wait on command queue until command processing is started, which is after the connect() completed the API-init handshake (so encoder has a server …
> Allow calls before connected

- src/io/decoder.ts
This PR addresses an issue where some fields that had variable number of elements were not decoding all their tokens, thereby causing later decoder errors, in `decodeMsg_COMPLETED_ORDER`.
The code in question was allocating a new Array ( `new Array(SIZE)` ) and expecting that a subsequent call to `.forEach` would in fact iterate `SIZE` times. The Array in this case was allocated with a capacity of `SIZE`, but did not itself contain elements that were able to be iterated over by `forEach`. A trivial example can be done in a JS console as follows:
`const c = new Array(10); c.forEach((i) => console.log("i", i))`
The code as written would expect to see 10 entries, similar to "i 0", "i 1", etc. What instead is output is nothing.
The code has been changed to follow the format used elsewhere in …
> Fixes for Completed Order Event

- src/io/socket.ts
See https://github.com/stoqey/ib/issues/58
I have no idea why nobody else had this problem yet, but looks like there are node.js versions / setups (idk?) that do not accept array on Socket.write.
So we give it a Buffer now.
> Fix "Invalid data, chunk must be a string or buffer"

- src/io/encoder.ts
The `primaryExch` field seems to be missing from `reqMktDepth` which is causing the API to hang.
This should fix it.
> Add missing primaryExch token to reqMktDepth

- src/core/io/controller.ts
When max_req_per_second is not set on config, we do not enforce any rate limit. 
This can cause IB Gateway to hang up if the App sends out too many requests simultaneously. 
This change enforces a 40 message per second limit (official TWS limit is 50).
This is only is a simply send [n] chunks than wait for the rest of the second algorithm, so it send a burst of messages first and than it wait for next tick.
I will keep a close eye on it to see if still get those Gateway hangs - if yes, we might need to add a traffic-shaping to get rid of the msg-burst and distributed packages evenly across the send-timeframe... but up to now it looks ok. No more hangs when I push my 100 market data requests into the API all at once.
> Enforce rate limit if not configured from external

- src/api-next/api-next.ts
- src/api-next/common/error.ts
- src/api-next/index.ts
- src/api-next/market/market-data.ts
- src/api-next/position/position.ts
- src/core/api-next/api/market/mutable-market-data.ts
- src/core/api-next/auto-connection.ts
- src/core/api-next/console-logger.ts
- src/core/api-next/subscription-registry.ts
- src/core/api-next/subscription.ts
- src/index.ts
- src/tests/unit/api-next/get-account-summary.test.ts
- src/tests/unit/api-next/get-contract-details.test.ts
- src/tests/unit/api-next/get-current-time.test.ts
- src/tests/unit/api-next/get-managed-accounts.test.ts
- src/tests/unit/api-next/get-market-data.test.ts
- src/tests/unit/api-next/get-pnl-signle.test.ts
- src/tests/unit/api-next/get-pnl.test.ts
- src/tests/unit/api-next/get-positions.test.ts
- src/tools/account-summary.ts
This PR has various changes related to IBApiNext, most are cosmetics.
In Detail:
- Export all IBApiNext types on the root-level index.ts
Some of the IBApiNext type where missing on root index.ts so you had to do stuff like 
```
import {something} from "@stoqey/ib/dist/somthing"
```
All IBApiNext type now exported via the root index.ts, so all you need
import * as IB from "@stoqey/ib"
- Make connection watchdog more robust again heavy message bursts.
The connection watchdog did rely on a sending a TWS time request and receiving an answer until the watchdog timeout.
During heavy message burst, it can happen that the request is stuck on the rater limiter, response does not arrive in time and watchdog triggers the re-connect. If have changed it so that now we measure the ingress timestamp of …
> Various IBApiNext improvments.

- README.md
- General formatting
- Fixed typo in first JS example
- Added 'js' type to second JS example
- Replaced `<your_account_id>` with valid JavaScript (`'YOUR_ACCOUNT_ID'`)
- Fixed typo `posistions` -> `positions`
> Fixed formatting + JS examples in README.md

- .vscode/launch.json
- .vscode/tasks.json
- api.Dockerfile
- package.json
- src/tools/account-summary.ts
- src/tools/common/ib-api-next-app.ts
- src/tools/market-data.ts
- yarn.lock
This PR has no functional change, but makes it easier to develop / debug the lib code.
The build task (Shift+Ctrl+B) now runs tsc -watch instead of ts-node-dev.
Have added launch tasks for all shell tools and a task to launch the currently open jest file on debugger.
Looks like this on VSCode now:
Select the task and press F5 to debug it.
Remove the obsolete package dependences + some cosmetics on the shell tools.
> Improve dev env

- package.json
v1.1.38 give the following error on my app:
```
Error: Cannot find module 'colors'
Require stack:
- c:\srcmfr\waytrade\ib-api-service\node_modules\@stoqey\ib\dist\core\api-next\console-logger.js
- c:\srcmfr\waytrade\ib-api-service\node_modules\@stoqey\ib\dist\api-next\api-next.js
- c:\srcmfr\waytrade\ib-api-service\node_modules\@stoqey\ib\dist\api-next\index.js
- c:\srcmfr\waytrade\ib-api-service\node_modules\@stoqey\ib\dist\index.js
- c:\srcmfr\waytrade\ib-api-service\dist\controllers\ib-api.controller.js
- c:\srcmfr\waytrade\ib-api-service\dist\controllers\index.js
- c:\srcmfr\waytrade\ib-api-service\dist\app.js
- c:\srcmfr\waytrade\ib-api-service\dist\index.js
- c:\srcmfr\waytrade\ib-api-service\dist\run.js
```
It is because of cleanup of the module dependencies. We need colors module, …
> Add dependency to colors

- .vscode/launch.json
- src/api-next/api-next.ts
- src/core/api-next/auto-connection.ts
- src/tests/unit/api-next/get-historical-data-updates.test.ts
- src/tests/unit/api-next/get-historical-data.test.ts
- src/tools/common/ib-api-next-app.ts
- src/tools/historical-data-updates.ts
- src/tools/historical-data.ts
This PR adds support for getting historic data to IBApiNext.
New functions:
- ` getHistoricalData: Promise<Bar[]>`
- `getHistoricalDataUpdates: Observable<Bar>`
Also I did a small tweak on connection watchdog: increased timeout value to 10s and doubled request frequency. 
This is to avoid connection drops during outside trading hours, when TWS behaves 'laggy', like e.g. on weekends as of right now for me (takes up 4-5s for TWS to response to a request - only happens very randomly during market closed hours and goes away after some time automatically - so increased our watchdog thresholds to survive such phases w/o constant re-connection attempts).
> IBApiNext: Add support for getting historic data 

- src/tests/unit/api/order/placeOrder.test.ts
Added test (and sample) code for placeOrder with PriceCondition.
Initiated by https://github.com/stoqey/ib/issues/78 to test if PriceCondition works and have sample code.
btw.. need to ping my broker again, completely forgot about the paper-accounts.. at some point those tests should actually run on CI.
> Add test (and sample) code for placeOrder with PriceCondition

- src/api-next/api-next.ts
- src/api/api.ts
- src/core/api-next/auto-connection.ts
- src/core/io/controller.ts
I had random freezes of Gateway / TWS when sending out whole bunch of requests at once.
Was hunting this bug for quite some time now and finally found the reason for it: our rate-limiter doesn't limit anything (it's used wrong), causing TWS to tilt.
This PR does two changes:
- Fix the rate-limit function call, so that actually does limit rate.
- Instead of limiting n (default 40) request per 1000ms, we now limit n/10 per 100ms. So instead of sending 40 request in 1ms and than do nothing for 999ms, we now split it into 100ms blocks. Throughput is still same, but we shape traffic-bursts.
> Fix rate limiter

- src/api-next/api-next.ts
- src/core/api-next/auto-connection.ts
- src/core/api-next/logger.ts
Just stumbled over a small, but very important detail on TWS doc:
https://interactivebrokers.github.io/tws-api/message_codes.html
`The TWS uses the IBApi.EWrapper.error method not only to deliver errors but also warnings or informative messages. This is done mostly for simplicity's sake `
.. but also warnings ...
Don't understand how this will simplify anything, but anyhow.. we must handle it. Right now all error callback dispatch into the rxjs subject as an error, so error callback is called and subscription is canceled. Not good if this is only warning, because subscription actually works, so no need to cancel.
We now handle error codes from 2100 to 2999 as warnings and log it, but we do not emit an error to rxjs.
PR also has a fix for the ApiNext logger (error and warn was converted to …
> IBApiNext: Handle warning codes properly

- .vscode/launch.json
- src/api-next/api-next.ts
- src/api/historical/historicalTickBidAsk.ts
- src/core/io/decoder.ts
- src/tests/unit/api-next/get-historical-ticks-bid-ask.test.ts
- src/tests/unit/api-next/get-historical-ticks-last.test.ts
- src/tests/unit/api-next/get-historical-ticks-mid.test.ts
- src/tools/historical-data-updates.ts
- src/tools/historical-data.ts
- src/tools/historical-ticks-bid-ask.ts
- src/tools/historical-ticks-last.ts
- src/tools/historical-ticks-mid.ts
Follow-up PR to https://github.com/stoqey/ib/pull/88 to get historic ticks fully supported.
Fixes:
- Fix HISTORICAL_TICKS decoder
New added functions:
```
IBApiNext.getHistoricalTicksMid(
contract: Contract,
startDateTime: string,
endDateTime: string,
numberOfTicks: number,
useRTH: number
): Observable<HistoricalTick[]>
```
```
IBApiNext.getHistoricalTicksBidAsk(
contract: Contract,
startDateTime: string,
endDateTime: string,
numberOfTicks: number,
useRTH: number,
ignoreSize: boolean
): Observable<HistoricalTickBidAsk[]>
```
```
IBApiNext.getHistoricalTicksLast(
contract: Contract,
startDateTime: string,
endDateTime: string,
numberOfTicks: number,
useRTH: number
): Observable<HistoricalTickLast[]>
```
New added tools:
- /dist/tools/historical-ticks-mid.js
- …
> IBApiNext: Add support for getting historical ticks and fix HISTORICAL_TICKS decoder

- README.md
- package.json
- src/api-next/api-next.ts
- src/tools/account-summary.ts
- src/tools/contract-details.ts
- src/tools/historical-ticks-bid-ask.ts
- src/tools/historical-ticks-last.ts
- src/tools/historical-ticks-mid.ts
- src/tools/pnl-single.ts
- src/tools/pnl.ts
- src/tools/positions.ts
- yarn.lock
Update to RxJX 7.
Changes:
- Obersable.toPromise has been deprecated. Replaced with `lastValueFrom`
I have added some extra comment to tools code that us lastValueFrom, to explain that you could also get incremental updates instead of waiting for complete / lastValueFrom.
- Added a new section to README, explaining different type of IBApiNext functions and how to use lastValueFrom with it.
> Update to RxJS 7.1

- src/api-next/api-next.ts
Does some code cleanup on IBApiNext code:
As discussed on slack:
- Remove take(1) operators on pipes. There is no more need for it, as it handled by .complete() call + lastValueFrom now.
As discussed on slack:
- Remove unnecessary subscriptions.clear() on callbacks, subscriptions will cleanup itself after completed.
During discussion on slack this came to my mind:
If you run a one-host Promise function, like getCurrentTime() 100x times in a loop, we will send 100 reqCurrentTime to TWS and first response will resolve it all.. => there is no real point on sending 100 reqCurrentTime. The first getCurrentTime() should send reqCurrentTime and all other 99 getCurrentTime() should just join waiting for response, instance of sending same request again. Solve that by using a hard-coded …
> IBApiNext code cleanup

- .vscode/launch.json
- src/api-next/api-next.ts
- src/api/api.ts
- src/api/data/enum/duration-unit.ts
- src/core/io/encoder.ts
- src/index.ts
- src/tests/unit/api-next/get-histogram-data.test.ts
- src/tools/histogram-data.ts
New functions:
`- IBApiNext.getHistogramData(contract: Contract, useRTH: boolean, duration: number, durationUnit: DurationUnit): Promise<HistogramEntry[]>`
New types / enums:
- DurationUnit
New tools:
- histogram-data.js
New tests (RxJS wrappers only):
get-histogram-data.test.ts
> IBApiNext: add support for getting histogram data

- .vscode/launch.json
- src/api-next/api-next.ts
- src/api/api.ts
- src/core/io/encoder.ts
- src/tests/unit/api-next/get-head-timestamp.test.ts
- src/tools/get-head-timestamp.ts
Fixes:
- fix reqHeadTimestamp function / encoder.
New functions:
`- IBApiNext.getHeadTimestamp(): Promise<number>`
New tools:
- get-head-timestamp.js
New tests (RxJS wrappers only):
get-head-timestamp.test.ts
> IBApiNext: add getHeadTimestamp

- README.md
- package.json
- src/api-next/api-next.ts
- src/api-next/market/market-data.ts
- src/api-next/position/position.ts
- src/api/api.ts
- src/api/data/container/soft-dollar-tier.ts
- src/api/order/orderComboLeg.ts
- src/core/io/decoder.ts
- src/core/io/encoder.ts
**This PR introduces a breaking change**
Because of the breaking change, I have pushed version to 1.2.0
Since we receive too many questions & "bug reports" about values set to Number.MAX_VALUE, we will drop this and use undefined instead. Number.MAX_VALUE was used for values that are not available. It was implemented like that to be in-sync with the official TWS Java API, however checking Number.MAX_VALUE is very uncommon in JScript/TS as everyone would expect `undefined` instead.
So this PR removes Number.MAX_VALUE and replaces it with undefined.
Affects:
IBApi decoder: readDoubleMax / readIntMax has been replaced with readDoubleOrUndefined / readIntOrUndefined
IBApi encoder: encoder still supports Number.MAX_VALUE and will continue to do so for some time. This is to avoid that we submit …
> Replace Number.MAX_VALUE with undefined.

- src/api-next/api-next.ts
- src/api/api.ts
- src/api/historical/bar-size-setting.ts
- src/core/io/encoder.ts
- src/tests/unit/api-next/get-historical-data-updates.test.ts
- src/tests/unit/api-next/get-historical-data.test.ts
- src/tools/historical-data-updates.ts
- src/tools/historical-data.ts
I added the allowed bar size settings in order to support developers with auto-completion in code. I took the "Valid Bar Sizes" from here: https://interactivebrokers.github.io/tws-api/historical_bars.html
> Add strict types for valid bar size setting

- src/core/io/decoder.ts
Work-in-progress PR, not sloved yet.
See https://github.com/stoqey/ib/issues/122
How to test:
Copy this to start() of some app on tools folder ad run it:
```
import { Decoder } from "../core/io/decoder";
..
start(): void {
const dec = new Decoder({
serverVersion: 164,
emitEvent(eventName: EventName, ...args: unknown[]) {
return;
},
emitError(errMsg: string, code: number, reqId: number) {
return;
},
emitInfo(message: string) {
return;
},
});
dec.enqueueMessage([
"5",
"19",
"172520988",
"XRTK",
"STK",
"",
"0",
"?",
"",
"CSFBALGO",
"USD",
"XRTK",
"NMS",
"SELL",
"300",
"LMT",
"3.95",
"0.0",
"DAY",
"",
"UXXXXXXXX",
"",
"0",
"",
"0",
"236990421",
"0",
"0",
"0",
"",
"236990421.0/UXXXXXXXX/100",
"",
"",
"",
"",
"",
"",
"0",
"",
"",
"0",
"",
"-1",
"0",
"",
"",
"",
"",
"",
"",
"0",
"0",
"0",
"", …
```
> Fix OPEN_ORDER decoding

- src/common/configuration.ts
Hi!
When the yarn + PnP is used, `@stoqey/ib` fails to ignore the configuration file read error, because the `errno` is undefined and the error is thrown.
```text
/home/user/dev/project/.pnp.cjs:11799
return Object.assign(new Error(`${code}: ${message}`), {code});
^
Error: ENOENT: no such file or directory, open '/node_modules/@stoqey/ib/config/default.json'
at makeError$1 (/home/user/dev/project/.pnp.cjs:11799:24)
at ENOENT (/home/user/dev/project/.pnp.cjs:11814:10)
at ZipFS.resolveFilename (/home/user/dev/project/.pnp.cjs:13355:15)
at ZipFS.readFileBuffer (/home/user/dev/project/.pnp.cjs:13761:28)
at ZipFS.readFileSync (/home/user/dev/project/.pnp.cjs:13755:23)
at /home/user/dev/project/.pnp.cjs:14750:20
at /home/user/dev/project/.pnp.cjs:14840:60
at ZipOpenFS.getZipSync …
```
> fix: Ignore configuration file read error, when yarn+PnP is used

- src/core/io/encoder.ts
- src/tests/unit/api/head-timestamp.test.ts
- src/tests/unit/api/histogram-data.test.ts
Adapted the encoding of a contract to match the code of the Java client. Fixed the order of values in reqHeadTimestamp and reqHistogramData to match the Java client.
I added unit tests, which work, but I could not get the full test suite to pass locally (e.g. requesting News). Probably some account restrictions.
> Fixed reqHeadTimestamp and reqHistogramData

- .codeclimate.yml
- .vscode/settings.json
- package.json
- src/common/errorCode.ts
- src/core/io/decoder.ts
- src/core/io/encoder.ts
- src/tests/unit/api-next-live/get-contract-details.test.ts
- src/tests/unit/api-next-live/subscription-registry.test.ts
- src/tests/unit/api-next/get-contract-details.test.ts
- src/tests/unit/api/head-timestamp.test.ts
- src/tests/unit/api/histogram-data.test.ts
- src/tests/unit/api/historical-data.test.ts
- src/tests/unit/api/market-data.test.ts
- src/tests/unit/api/market-scanner.test.ts
- src/tests/unit/api/order/reqCompletedOrders.test.ts
- src/tests/unit/contracts.ts
- yarn.lock
Issue #201 fixed
Test cases improved
Packages upgrade
> Issue "Decoding error on COMPLETED_ORDER #201" fixed

- .codeclimate.yml
- .github/workflows/check.yml
- .github/workflows/publish.yml
- package.json
- src/api/data/enum/sec-type.ts
- src/core/api-next/subscription-registry.ts
- src/core/io/decoder.ts
- src/tests/unit/api-next-live/get-contract-details.test.ts
- src/tests/unit/api/order/placeOrder.test.ts
- yarn.lock
issue #210 fix
placeOrder test suite improved
> Ryl20240309

- src/api/api.ts
There are additional parameters passed to this function that aren't being passed through. I updated the listener definition.
> Correct Event.tickByTickAllLast event listener definition

- package.json
- src/api-next/api-next.ts
- src/api-next/common/error.ts
- src/api/contract/priceIncrement.ts
- src/common/errorCode.ts
- src/core/api-next/subscription-registry.ts
- src/core/api-next/subscription.ts
- src/core/io/controller.ts
- src/core/io/decoder.ts
- src/core/io/encoder.ts
- src/core/io/socket.ts
- src/index.ts
- src/tests/unit/api-next-live/get-contract-details.test.ts
- src/tests/unit/api-next-live/get-current-time.test.ts
- src/tests/unit/api-next-live/get-historical-ticks.test.ts
- src/tests/unit/api-next-live/get-managed-accounts.test.ts
- src/tests/unit/api-next-live/get-market-rule.test.ts
- src/tests/unit/api-next-live/get-user-info.test.ts
- src/tests/unit/api-next-live/subscription-registry.test.ts
- src/tests/unit/api-next/get-account-summary.test.ts
- src/tests/unit/api-next/get-account-updates.test.ts
- src/tests/unit/api-next/get-historical-data.test.ts
- src/tests/unit/api-next/next-valid-order-id.test.ts
- src/tests/unit/api/historical-data.test.ts
- src/tests/unit/api/market-scanner.test.ts
- src/tests/unit/api/order/cancelOrder.test.ts
- yarn.lock
Fixes reqMarketRule in ibnext #230 
```
Test Suites: 2 failed, 47 passed, 49 total
Tests:       2 failed, 120 passed, 122 total
Snapshots:   0 total
Time:        103.688 s
```
> Implement getMarketRule and minor improvements

- src/core/io/decoder.ts
BUG: There's a bug in TWS, when a contract has a multiplier as a float e.g `0.1`, ib returns it as `0`
**FIX: replace readInt with readDouble**
PS: `decodeMsg_SECURITY_DEFINITION_OPTION_PARAMETER` had a `readStr` i changed it to `readDouble` too
> fix(multiplier): readInt to readDouble

- src/api-next/api-next.ts
- src/common/errorCode.ts
- src/core/api-next/auto-connection.ts
BUGS: 
1. 
- When you set a `reconnectInterval: 1000, connectionWatchdogInterval: 1`, even if you're connected runWatchdog disconnects and tries to create a new connection.
- **FIX:** If we already have a connection, no need to trigger reconnect, we should keep the current connection.
2. 
- When you're connected and you lose internet connection (e.i TWS loses connection to IBKR servers), it takes a while for `Socket.onEnd` to get triggered, but TWS already sends code 1100 and 2110)
- **FIX**: if we receive codes 1100/2110, it means we're not connected to the server, we trigger watchdog to try and reconnect.
> fix(watchdog): keep connected, reconnect with code 1100/2110

- src/core/io/encoder.ts
- src/tests/unit/api/historical-news.test.ts
#235 
BUG: duplicate endDate token and wrong message id `REQ_NEWS_PROVIDERS,`
**FIX**: removed duplicate, used correct message id `REQ_HISTORICAL_NEWS` and added tests to get news providers + a few PLTR news data
> fix(reqHistoricalNews): duplicate endDate token, correct msgId
